- hosts: all
  become: yes
  tasks:
          
    - name: "Atualizando pacotes"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
