- hosts: all
  become: yes
  tasks:
          
    - name: "Atualizando pacotes"
      become: yes
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #Um dia
        
    - name: install ngnix
      apt: name=nginx state=latest
    - name: start nginx
      service:
          name: nginx
          state: started


    - name: "Fazendo downlaod do template"
      get_url:
        url: "https://github.com/startbootstrap/startbootstrap-sb-admin-2/archive/gh-pages.zip"
        dest: "/tmp/gh-pages.zip"

    - name: "Fazendo descompactação dos template
      unarchive:
        src: "/tmp/gh-pages.zip"
        dest: "/var/www"
        remote_src: yes
      become: yes
